"""empty message

Revision ID: 1e7bc8a5d33a
Revises: fcfc0e623b7a
Create Date: 2025-05-31 07:49:13.742862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e7bc8a5d33a'
down_revision = 'fcfc0e623b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_completion', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_approved', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_completion')

    # ### end Alembic commands ###
