"""empty message

Revision ID: 26411b05ecf8
Revises: 4afc565949d1
Create Date: 2025-04-13 22:02:28.164315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26411b05ecf8'
down_revision = '4afc565949d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_type_name'), ['name'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['course_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_type_id'), ['type_id'], unique=False)

    op.create_table('course_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['course_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_list_type_id'), ['type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_list_type_id'))

    op.drop_table('course_list')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_type_id'))
        batch_op.drop_index(batch_op.f('ix_course_name'))

    op.drop_table('course')
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_type_name'))

    op.drop_table('course_type')
    # ### end Alembic commands ###
