"""empty message

Revision ID: 31225a820f7e
Revises: 39873caa3d62
Create Date: 2025-05-31 08:55:55.235052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31225a820f7e'
down_revision = '39873caa3d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_departments', schema=None) as batch_op:
        batch_op.drop_constraint('teachers_departments_department_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teachers_departments_department_id_fkey', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###
