"""empty message

Revision ID: 39873caa3d62
Revises: 9c4785df694e
Create Date: 2025-05-31 08:51:58.865412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39873caa3d62'
down_revision = '9c4785df694e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.drop_index('ix_course_type_deadline')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_course_type_deadline', ['deadline'], unique=False)

    # ### end Alembic commands ###
