"""empty message

Revision ID: 4f9e17df04bf
Revises: b88b1151e45c
Create Date: 2025-06-01 09:03:40.707591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9e17df04bf'
down_revision = 'b88b1151e45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirming_document', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_teacher_course_confirming_document'), ['confirming_document'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_course_confirming_document'))
        batch_op.drop_column('confirming_document')

    # ### end Alembic commands ###
