"""ver1

Revision ID: 62380bc1a269
Revises: 8a1e5f4e8f69
Create Date: 2025-03-30 20:54:19.701352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62380bc1a269'
down_revision = '8a1e5f4e8f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['faculty_id'], ['id'])

    # ### end Alembic commands ###
