"""empty message

Revision ID: 7e5b40525afd
Revises: 9669379fa69a
Create Date: 2025-05-02 16:15:51.984970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5b40525afd'
down_revision = '9669379fa69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.drop_index('ix_course_type_name')

    op.drop_table('course_type')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_message')
        batch_op.drop_index('ix_notification_user_id')

    op.drop_table('notification')
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_course_course_id')
        batch_op.drop_index('ix_teacher_course_teacher_id')

    op.drop_table('teacher_course')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('ix_course_course_type_id')
        batch_op.drop_index('ix_course_is_included')
        batch_op.drop_index('ix_course_name')

    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('course_type_id', sa.INTEGER(), nullable=False),
    sa.Column('is_included', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('ix_course_name', ['name'], unique=1)
        batch_op.create_index('ix_course_is_included', ['is_included'], unique=False)
        batch_op.create_index('ix_course_course_type_id', ['course_type_id'], unique=False)

    op.create_table('teacher_course',
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('sertificate_path', sa.VARCHAR(length=260), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id'),
    sa.UniqueConstraint('sertificate_path')
    )
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_course_teacher_id', ['teacher_id'], unique=False)
        batch_op.create_index('ix_teacher_course_course_id', ['course_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('has_read', sa.BOOLEAN(), nullable=False),
    sa.Column('time_sent', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notification_message', ['message'], unique=1)

    op.create_table('course_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.create_index('ix_course_type_name', ['name'], unique=1)

    # ### end Alembic commands ###
