"""empty message

Revision ID: 9c4785df694e
Revises: 1e7bc8a5d33a
Create Date: 2025-05-31 08:49:30.581784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c4785df694e'
down_revision = '1e7bc8a5d33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.alter_column('date_completion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.alter_column('date_completion',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
