"""empty message

Revision ID: b88b1151e45c
Revises: ea70de0222c6
Create Date: 2025-05-31 21:28:04.480408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88b1151e45c'
down_revision = 'ea70de0222c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', sa.String(length=260), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###
