"""empty message

Revision ID: d12242f2a615
Revises: 2cc7ac1c2283
Create Date: 2025-05-11 10:38:08.503048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12242f2a615'
down_revision = '2cc7ac1c2283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_type_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_type_name'), ['name'], unique=True)

    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('is_fired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_fired'), ['is_fired'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('course_type_id', sa.Integer(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_course_type_id'), ['course_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_is_included'), ['is_included'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_name'), ['name'], unique=True)

    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_name'), ['name'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('has_read', sa.Boolean(), nullable=False),
    sa.Column('time_sent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_message'), ['message'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_time_sent'), ['time_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('teacher_course',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sertificate_path', sa.String(length=260), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id'),
    sa.UniqueConstraint('sertificate_path')
    )
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_course_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_course_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('teachers_departments',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_departments')
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_course_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_course_course_id'))

    op.drop_table('teacher_course')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_time_sent'))
        batch_op.drop_index(batch_op.f('ix_notification_message'))

    op.drop_table('notification')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_name'))
        batch_op.drop_index(batch_op.f('ix_department_faculty_id'))

    op.drop_table('department')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_name'))
        batch_op.drop_index(batch_op.f('ix_course_is_included'))
        batch_op.drop_index(batch_op.f('ix_course_course_type_id'))

    op.drop_table('course')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_is_fired'))

    op.drop_table('user')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_name'))

    op.drop_table('faculty')
    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_type_name'))
        batch_op.drop_index(batch_op.f('ix_course_type_deadline'))

    op.drop_table('course_type')
    # ### end Alembic commands ###
