"""empty message

Revision ID: ea70de0222c6
Revises: 31225a820f7e
Create Date: 2025-05-31 21:16:54.637959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea70de0222c6'
down_revision = '31225a820f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('ix_course_is_included')
        batch_op.drop_column('is_included')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_included', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_course_is_included', ['is_included'], unique=False)

    # ### end Alembic commands ###
